# -*- coding: utf-8 -*-
"""Pandas 612.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18cJJOHtWmwG0SQM6QyyT3EnkNJ7ZVdyL
"""

import pandas as pd

Data = {
    "Familiya": ["Ziyotaliyev", "Mahmudjonova"],
    "Ism": ["Rustamjon", "Robiyaxon"],
    "Yosh": [21, 17],
    "Manzil": ["Qoshtepa tumani", "Margilon shaxar"],
    "Kursi": ["612-24", "1-Kurs"]
}
baza=pd.DataFrame(Data)
print(baza)

filter=[baza["Yosh"]<30]
print(filter)

filter=baza[baza["Manzil"] == "Margilon shaxar"]

titanicdata=pd.read_csv("titanic.csv")
print(titanicdata)

filtr=titanicdata[titanicdata['Sex']=="female"]
print(filtr)

filtr=titanicdata[titanicdata['Age'] < 15]
print(filtr)
